# 文件存储路径（根据系统调整）
file:
  upload-dir: ./files
spring:
  web:
    resources:
      static-locations: classpath:/static,classpath:/dist,file:./files
  servlet:
    multipart:
      max-file-size: 100MB  # 单文件大小限制

server:
  host: http://127.0.0.1
  port: 1082
  # 固定服务器地址
  auth-server: https://kloping.top/

# 认证配置
auth:
  app-id: 101689742 # 申请的APPID
  app-secret: FIpktt8AsZJrqgU #申请的secret
  ## 你部署的服务器的地址
  redirect-uri: https://file.kloping.top/auth/callback

logging:
  pattern:
    console: "%clr([%thread]){blue} %clr(%-32.32logger{32}){magenta} %clr(%d{yyyy-MM-dd HH:mm:ss}){red} %clr(%-5p): %msg%n"
    file: "[%thread] %-32.32logger{32} %d{yyyy-MM-dd HH:mm:ss} %-5p: %msg%n"
  file:
    # 输出的log文件名
    name: ./logs/slf4j.log
    # 输出的文件的路径
    path: logs
    # 限制日志文件的大小
    # 日志的保存天数
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7